"""Storage for assets that must never be publicly readable.

WHY THIS IS NOT PART OF FileStorage
-----------------------------------
`file_storage.FileStorage` is image-shaped in three ways that are all wrong
here, and none of them are incidental:

  - `save_image()` validates the filename against ALLOWED_IMAGE_EXTENSIONS
  - it recompresses whatever it is given through Pillow into a JPEG
  - it returns a **public URL**

A playbook PDF is not an image, must not be transcoded, and above all must not
be addressable. Widening that interface to accommodate it would leave one class
whose contract is "returns a public URL" for half its methods and "must never
return a public URL" for the other half - a distinction too important to depend
on a caller picking the right method name.

So this is a separate interface with a separate implementation and a separate
bucket. It returns **opaque storage keys**, never URLs. Nothing in this module
can produce a URL, because there is nothing here to produce one from.

WHERE PRIVACY ACTUALLY COMES FROM
---------------------------------
Not from this code. A key called `private/abc.pdf` in a bucket whose root is
bound to a public hostname is world-readable, prefix or no prefix. Privacy is a
property of the bucket's configuration:

  - production: R2_PRIVATE_BUCKET_NAME must be a bucket with NO public access
    binding. There is deliberately no config value for a public URL base for
    it, so no code path can construct one even by mistake.
  - local dev: PRIVATE_UPLOAD_FOLDER must be outside UPLOAD_FOLDER, which
    `create_app` serves wholesale at /uploads/<path:filename>. There is a test
    that fails if the two ever overlap.

See docs/DESIGN-playbook-quiz.md §7a.
"""

from __future__ import annotations

import secrets
from abc import ABC, abstractmethod
from pathlib import Path

import boto3
from flask import current_app

#: Keys are random, not derived from anything about the file. A key derived
#: from an id, an org or a filename would be guessable, and the only thing
#: standing between an attacker and a playbook - once a bucket is
#: misconfigured, which is the failure mode worth defending against - is
#: whether the key can be guessed. 32 bytes is far past brute force.
KEY_ENTROPY_BYTES = 32


def new_storage_key(extension: str) -> str:
    """An opaque, unguessable key. `extension` is for operator sanity when
    looking at a bucket listing; nothing reads it back."""
    safe_extension = "".join(c for c in extension.lower() if c.isalnum())[:8] or "bin"
    return f"{secrets.token_hex(KEY_ENTROPY_BYTES)}.{safe_extension}"


class PrivateAssetStorage(ABC):
    """Opaque byte storage. No URLs, in or out."""

    @abstractmethod
    def save_private(self, data: bytes, *, content_type: str, extension: str) -> str:
        """Store bytes and return the key they can be read back with."""

    @abstractmethod
    def load_private(self, key: str) -> bytes | None:
        """Read bytes back. Returns None if the key does not exist."""

    def private_size(self, key: str) -> int | None:
        """The object's length in bytes, WITHOUT downloading it.

        Needed for a `Content-Range` total, and for deciding whether a
        requested range is satisfiable at all. The default answers by loading
        the object, so a backend that cannot do better still works; both
        backends below override it with something cheap.
        """
        data = self.load_private(key)
        return None if data is None else len(data)

    def load_private_range(self, key: str, start: int, end: int) -> bytes | None:
        """Bytes `start`..`end` INCLUSIVE, without fetching the whole object.

        THE POINT OF THIS METHOD. iOS Safari opens a video with
        `Range: bytes=0-1`, and the naive implementation - fetch everything,
        then slice - downloaded several megabytes from object storage to
        answer with two bytes, then did it again for the next request. The
        player waited through both.

        The default below is that naive behaviour, kept only so a backend
        without ranged reads is still correct rather than broken. Both real
        backends override it.
        """
        data = self.load_private(key)
        if data is None:
            return None
        return data[start : end + 1]

    @abstractmethod
    def delete_private(self, key: str) -> None:
        """Remove an asset. Idempotent - no error if it is already gone."""


class LocalPrivateStorage(PrivateAssetStorage):
    """Disk-backed, for local development and tests."""

    def __init__(self, private_folder: str):
        self.private_folder = Path(private_folder)

    def _path_for(self, key: str) -> Path:
        # Keys are generated by new_storage_key() and contain only hex and a
        # short extension, but this is the one place a caller-supplied string
        # becomes a filesystem path, so it is checked rather than trusted:
        # a key containing ".." or a separator must not escape the folder.
        candidate = (self.private_folder / key).resolve()
        root = self.private_folder.resolve()
        if root != candidate.parent:
            raise ValueError("Refusing a storage key that escapes the private folder")
        return candidate

    def save_private(self, data: bytes, *, content_type: str, extension: str) -> str:
        key = new_storage_key(extension)
        self.private_folder.mkdir(parents=True, exist_ok=True)
        self._path_for(key).write_bytes(data)
        return key

    def load_private(self, key: str) -> bytes | None:
        try:
            return self._path_for(key).read_bytes()
        except (OSError, ValueError):
            return None

    def private_size(self, key: str) -> int | None:
        try:
            return self._path_for(key).stat().st_size
        except (OSError, ValueError):
            return None

    def load_private_range(self, key: str, start: int, end: int) -> bytes | None:
        # Seek and read, so dev behaves like production rather than hiding a
        # full read behind a fast disk.
        try:
            with self._path_for(key).open("rb") as handle:
                handle.seek(start)
                return handle.read(end - start + 1)
        except (OSError, ValueError):
            return None

    def delete_private(self, key: str) -> None:
        try:
            self._path_for(key).unlink(missing_ok=True)
        except (OSError, ValueError):
            # Deletion is best-effort by design: see documents.py's delete
            # route for why an un-deletable object must not fail the request.
            pass


class S3PrivateStorage(PrivateAssetStorage):
    """A private S3-compatible bucket (built against Cloudflare R2).

    Note the absence of any `public_url_base` parameter. That is the point.
    """

    def __init__(
        self,
        account_id: str,
        access_key_id: str,
        secret_access_key: str,
        bucket_name: str,
    ):
        self.bucket_name = bucket_name
        self.client = boto3.client(
            "s3",
            endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
            aws_access_key_id=access_key_id,
            aws_secret_access_key=secret_access_key,
            region_name="auto",
        )

    def save_private(self, data: bytes, *, content_type: str, extension: str) -> str:
        key = new_storage_key(extension)
        self.client.put_object(
            Bucket=self.bucket_name,
            Key=key,
            Body=data,
            ContentType=content_type,
        )
        return key

    def load_private(self, key: str) -> bytes | None:
        try:
            return self.client.get_object(Bucket=self.bucket_name, Key=key)["Body"].read()
        except Exception:
            # Broad on purpose, matching S3FileStorage.load_image_bytes:
            # botocore raises its own hierarchy for "not found" alongside
            # network and credential errors, and a caller only ever needs to
            # know whether it got the bytes.
            return None

    def private_size(self, key: str) -> int | None:
        """HEAD, not GET. Cheap, and it does not move the bytes."""
        try:
            return int(self.client.head_object(Bucket=self.bucket_name, Key=key)["ContentLength"])
        except Exception:
            # Same broad catch as load_private, and for the same reason: the
            # caller only needs to know whether it got an answer.
            return None

    def load_private_range(self, key: str, start: int, end: int) -> bytes | None:
        """A genuine ranged GET against R2.

        S3 and R2 both take an HTTP Range header on `get_object`, so only the
        requested bytes cross the network. This is the whole optimisation:
        answering `bytes=0-1` used to cost a full-object download.
        """
        try:
            response = self.client.get_object(
                Bucket=self.bucket_name,
                Key=key,
                Range=f"bytes={start}-{end}",
            )
            return response["Body"].read()
        except Exception:
            return None

    def delete_private(self, key: str) -> None:
        self.client.delete_object(Bucket=self.bucket_name, Key=key)


def get_private_storage() -> PrivateAssetStorage:
    if current_app.config["STORAGE_BACKEND"] == "s3":
        bucket = current_app.config.get("R2_PRIVATE_BUCKET_NAME")
        if not bucket:
            # Failing loudly is the whole point. Silently falling back to the
            # public bucket would put a playbook exactly where it must never
            # be, and would do it invisibly.
            raise RuntimeError(
                "R2_PRIVATE_BUCKET_NAME is not configured. Protected documents "
                "require a bucket with no public access binding - they must not "
                "be written to the public image bucket."
            )
        return S3PrivateStorage(
            account_id=current_app.config["R2_ACCOUNT_ID"],
            access_key_id=current_app.config["R2_ACCESS_KEY_ID"],
            secret_access_key=current_app.config["R2_SECRET_ACCESS_KEY"],
            bucket_name=bucket,
        )
    return LocalPrivateStorage(private_folder=current_app.config["PRIVATE_UPLOAD_FOLDER"])
