"""Add beta invites

Revision ID: 7daa062e13ee
Revises: a7fd4276c072
Create Date: 2026-08-19

WRITTEN BY HAND, NOT LEFT AS AUTOGENERATED. `flask db migrate` produced this
table correctly and then added a dozen changes nobody asked for: it wanted to
DROP the check constraints on `access_codes.mode`, `player_attempts.mode` and
`competition_sessions.status`, drop `uq_one_drawing_per_answer`, and flip the
uniqueness of two indexes - all unrelated to beta invites and all destructive.

That is autogenerate failing to recognise constraints this schema declares in
ways it cannot round-trip, not a real drift. Everything except the new table
has been removed. If a future migration here is autogenerated, read it before
trusting it.

Purely additive: one new table, no change to any existing one, so a downgrade
is a clean drop and nothing else has to be undone.
"""
from alembic import op
import sqlalchemy as sa


revision = '7daa062e13ee'
down_revision = 'a7fd4276c072'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'beta_invites',
        sa.Column('id', sa.Integer(), nullable=False),
        # SHA-256 hex is always 64 characters. The plaintext token is never
        # stored - see models/beta_invite.py.
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('token_prefix', sa.String(length=16), nullable=False),
        sa.Column('label', sa.String(length=200), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('created_by_coach_id', sa.Integer(), nullable=True),
        sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('redeemed_by_coach_id', sa.Integer(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        # SET NULL on both, matching organization_invites: a coach leaving the
        # program must not delete the record of invitations they issued or
        # redeemed.
        sa.ForeignKeyConstraint(
            ['created_by_coach_id'], ['coaches.id'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['redeemed_by_coach_id'], ['coaches.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # UNIQUE because two invites sharing a hash would mean the same token was
    # issued twice - and the index is what makes redemption's conditional
    # UPDATE cheap.
    op.create_index(
        op.f('ix_beta_invites_token_hash'), 'beta_invites', ['token_hash'], unique=True
    )


def downgrade():
    op.drop_index(op.f('ix_beta_invites_token_hash'), table_name='beta_invites')
    op.drop_table('beta_invites')
