"""Add access requests

Revision ID: c31f70a9d84b
Revises: 7daa062e13ee
Create Date: 2026-08-20

WRITTEN BY HAND, for the reason recorded in 7daa062e13ee. `flask db migrate`
builds this table correctly and then adds a pile of changes nobody asked for -
DROPping the check constraints on `access_codes.mode`, `player_attempts.mode`
and `competition_sessions.status`, dropping `uq_one_drawing_per_answer`, and
flipping the uniqueness of two indexes. That is autogenerate failing to
round-trip constraints this schema declares, not real drift. If a future
migration here is autogenerated, read it before trusting it.

Purely additive: one new table, no change to any existing one, so a downgrade
is a clean drop and nothing else has to be undone.
"""
from alembic import op
import sqlalchemy as sa


revision = 'c31f70a9d84b'
down_revision = '7daa062e13ee'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'access_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        # Nullable, and genuinely optional - see models/access_request.py.
        sa.Column('team', sa.String(length=200), nullable=True),
        sa.Column(
            'requested_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # UNIQUE is what makes asking twice harmless: the insert is ON CONFLICT DO
    # NOTHING, so a repeat submission keeps the FIRST request time instead of
    # creating a second row or raising at the person who clicked twice.
    op.create_index(
        op.f('ix_access_requests_email'), 'access_requests', ['email'], unique=True
    )


def downgrade():
    op.drop_index(op.f('ix_access_requests_email'), table_name='access_requests')
    op.drop_table('access_requests')
