"""Add beta invite expiry

Revision ID: d4c1e8b7a903
Revises: c3a8b0e2f915
Create Date: 2026-08-28

WRITTEN BY HAND, NOT AUTOGENERATED - see 7daa062e13ee for why autogenerate is
not trusted against this schema.

ONE NULLABLE COLUMN, AND THE NULL IS THE POINT. Every invite issued before
this migration was issued under a rule that said invites do not expire, and
back-filling a deadline onto them would silently kill invitations already sent
to real coaches. NULL therefore keeps its old meaning exactly - "this one never
expires" - and only invites created from now on carry a deadline.

Purely additive: no existing column changes, no data is rewritten, and the
downgrade is a clean drop.
"""
from alembic import op
import sqlalchemy as sa


revision = 'd4c1e8b7a903'
down_revision = 'c3a8b0e2f915'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "beta_invites",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade():
    op.drop_column("beta_invites", "expires_at")
