"""Add staff invite requests

Revision ID: e5c2a71bd490
Revises: c31f70a9d84b
Create Date: 2026-08-20

WRITTEN BY HAND, for the reason recorded in 7daa062e13ee: `flask db migrate`
builds the table correctly and then adds a pile of destructive changes nobody
asked for, including DROPping live check constraints. Read any autogenerated
migration here before trusting it.

Purely additive: one new table, no change to any existing one, so a downgrade
is a clean drop.
"""
from alembic import op
import sqlalchemy as sa


revision = 'e5c2a71bd490'
down_revision = 'c31f70a9d84b'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'staff_invite_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        # NOT NULL and never client-supplied - it is copied from the requesting
        # coach's own row. See models/staff_invite_request.py.
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('requested_by_coach_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column(
            'requested_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        # THE ONLY LINK TO A CREDENTIAL, and it points outward. There is no
        # column on this table that could ever hold a token, which is what
        # makes "a request is not an invite" structural rather than a promise.
        sa.Column('approved_invite_id', sa.Integer(), nullable=True),
        sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
        # SET NULL: a coach leaving must not delete the record of a colleague
        # they vouched for, especially one already approved.
        sa.ForeignKeyConstraint(
            ['requested_by_coach_id'], ['coaches.id'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['approved_invite_id'], ['organization_invites.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_staff_invite_requests_organization_id'),
        'staff_invite_requests',
        ['organization_id'],
    )
    # PENDING ROWS ONLY. Asking twice for the same person while the first ask
    # is still waiting is a double click, and DO NOTHING absorbs it. But a
    # DECIDED request must not block asking again - declining somebody in
    # August cannot mean they can never be added in September - so decided
    # rows fall out of the index entirely rather than being constrained.
    op.create_index(
        'uq_pending_staff_invite_request',
        'staff_invite_requests',
        ['organization_id', 'email'],
        unique=True,
        postgresql_where=sa.text('approved_at IS NULL AND declined_at IS NULL'),
    )


def downgrade():
    op.drop_index('uq_pending_staff_invite_request', table_name='staff_invite_requests')
    op.drop_index(
        op.f('ix_staff_invite_requests_organization_id'),
        table_name='staff_invite_requests',
    )
    op.drop_table('staff_invite_requests')
