"""Add beta invite token ciphertext

Revision ID: e5d2f9c4a771
Revises: d4c1e8b7a903
Create Date: 2026-08-27

WRITTEN BY HAND, NOT AUTOGENERATED - see 7daa062e13ee for why autogenerate is
not trusted against this schema.

ONE NULLABLE COLUMN, NO BACKFILL, AND THE NULL IS THE HONEST ANSWER. Every
invite issued before this migration was created under a model that stored only
a SHA-256, so its plaintext genuinely does not exist anywhere - not in a
backup, not in a log, nowhere. NULL means exactly that, and the Owner Dashboard
says so rather than implying the code could be dug out.

DOWNGRADE IS LOSSY IN ONE SPECIFIC WAY, and it is worth naming. Dropping the
column destroys the stored recoverability of any invite that had ciphertext:
the owner can no longer reopen those codes. It does NOT affect the invites
themselves - `token_hash` is untouched, so every outstanding code still
redeems, and a coach holding one is unaffected. A downgrade turns recoverable
invites back into legacy ones; it does not invalidate them.
"""
from alembic import op
import sqlalchemy as sa


revision = 'e5d2f9c4a771'
down_revision = 'd4c1e8b7a903'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "beta_invites",
        # Text rather than a sized String: a Fernet token's length depends on
        # the plaintext and the library's framing, and guessing a maximum is
        # how a future change gets truncated instead of rejected.
        sa.Column("token_ciphertext", sa.Text(), nullable=True),
    )


def downgrade():
    op.drop_column("beta_invites", "token_ciphertext")
